//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facebook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useri
    {
        public int ID { get; set; }
        public string emer { get; set; }
        public string mbiemer { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> AdminOrUser { get; set; }
        public string searchi { get; set; }
    }
}
